# Generated by Django 3.1.1 on 2020-10-12 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgpc_commande',
            name='COM_RES_ID',
            field=models.ManyToManyField(blank=True, related_name='est_associe_a', to='service.SGPC_RESERVATION'),
        ),
        migrations.AddField(
            model_name='sgpc_commande',
            name='COM_UTI_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sgpc_asso_com_pro',
            name='ACP_COMMANDE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.sgpc_commande'),
        ),
        migrations.AddField(
            model_name='sgpc_asso_com_pro',
            name='ACP_PRODUIT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.sgpc_produit'),
        ),
    ]
