# Generated by Django 3.1.1 on 2020-10-14 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20201012_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgpc_commande',
            name='COM_FRAIS_LIVRAISON',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
