# Generated by Django 3.1.1 on 2020-10-12 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SGPC_ASSO_SER_DEV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASD_PRIX_EFFECTIF', models.IntegerField(blank=True, null=True)),
                ('ASD_COMMENTAIRE', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SGPC_DEVIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEV_DATE', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SGPC_SERVICE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SER_NOM', models.CharField(max_length=50)),
                ('SER_PRIX_STANDARD', models.PositiveIntegerField()),
                ('SER_DESCRIPTION', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SGPC_RESERVATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RES_DATE', models.DateField(validators=[service.models.validate_date])),
                ('RES_STATUT', models.CharField(choices=[('Confirmé', 'Confirmé'), ('En attente de confirmation', 'En attente de confirmation'), ('Annulé', 'Annulé')], max_length=50)),
                ('RES_COM_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.sgpc_commande')),
                ('RES_DEV_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.sgpc_devis')),
                ('RES_SER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.sgpc_service')),
                ('RES_UTI_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sgpc_devis',
            name='DEV_SER',
            field=models.ManyToManyField(through='service.SGPC_ASSO_SER_DEV', to='service.SGPC_SERVICE'),
        ),
        migrations.AddField(
            model_name='sgpc_devis',
            name='DEV_UTI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sgpc_asso_ser_dev',
            name='ASD_DEV_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.sgpc_devis'),
        ),
        migrations.AddField(
            model_name='sgpc_asso_ser_dev',
            name='ASD_SER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.sgpc_service'),
        ),
    ]
